import poidet from '@poidet/eslint-config';

// Flat config generated by the @nuxt/eslint module — it knows this project's
// layout (srcDir, pages, layouts) and adds the Vue/Nuxt rule set.
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt(
	poidet({
		vue: true,
		typescript: true,
		// Markdown and stylesheets are owned by `prettier -c .` and stylelint;
		// letting ESLint format them too produces conflicting (circular) fixes.
		ignores: ['.nuxt', '.output', 'dist', 'node_modules', 'public', '**/*.md', '**/*.scss', '**/*.css']
	})
).append({
	name: 'project/overrides',
	rules: {
		// @nuxt/eslint targets eslint-plugin-vue 10, @poidet/eslint-config pins 9,
		// whose schema for this rule takes no options. Vue 3 allows multiple roots
		// anyway, so the rule is simply off.
		'vue/no-multiple-template-root': 'off',
		// Components are imported PascalCase and used kebab-case in templates.
		'vue/component-name-in-template-casing': ['error', 'kebab-case']
	}
});
