import antfu from '@antfu/eslint-config';
import prettier from 'eslint-plugin-prettier/recommended';
import simpleImportSort from 'eslint-plugin-simple-import-sort';

// Flat config generated by the @nuxt/eslint module — it knows this project's
// layout (srcDir, pages, layouts) and adds the Vue/Nuxt rule set.
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt(
	antfu({
		vue: true,
		typescript: true,
		// Prettier owns formatting (see `prettier` below and `prettier -c .` in
		// the lint script), so ESLint's own stylistic layer stays off.
		stylistic: false,
		jsonc: false,
		yaml: false,
		markdown: false,
		// Markdown and stylesheets belong to `prettier -c .` and stylelint;
		// having ESLint format them too produces circular fixes.
		ignores: ['.nuxt', '.output', 'dist', 'node_modules', 'public', '**/*.md', '**/*.scss', '**/*.css']
	})
		.append(prettier)
		.append({
			name: 'project/import-sort',
			plugins: { 'simple-import-sort': simpleImportSort },
			rules: {
				'simple-import-sort/imports': 'error',
				'simple-import-sort/exports': 'error',
				// Superseded by simple-import-sort.
				'perfectionist/sort-imports': 'off',
				'import/order': 'off'
			}
		})
).append({
	name: 'project/overrides',
	rules: {
		// Components are imported PascalCase and used kebab-case in templates.
		'vue/component-name-in-template-casing': ['error', 'kebab-case']
	}
});
